version: '3'

services:
  ids:
    image: vainnor/vzdc_ids_v2:1.0.0
    env_file:
      - stack.env
    ports:
      - "3001:3001"

  updater:
    image: vainnor/vzdc_ids_v2_updater:1.0.0
    env_file:
      - stack.env
    ports:
      - "3002:3002"
