version: '3.8'

services:
  website:
    image: your-website-image
    env_file:
      - ./website.env
    ports:
      - "3000:3000"
    depends_on:
      - db

  ids:
    image: your-ids-image
    env_file:
      - ./ids.env
    ports:
      - "3001:3001"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ids-v2
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
